# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'MEC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'MJRefresh', '~> 3.2.0'
	pod 'MJExtension', '~> 3.1.0'
	pod 'Masonry', '~> 1.1.0'
 	pod 'AFNetworking', '~> 3.2.1'
	pod 'SDWebImage', '~> 5.0.6'
	pod 'IQKeyboardManager', '~> 6.3.0'
	pod 'MBProgressHUD', '~> 1.1.0'

	pod 'Bugly', '~> 2.5.0'
	#pod 'YYText', '~> 1.0.7'

end
